version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: eduver-web
    ports:
      - "3006:80"
    volumes:
      # Mount this project directory to Nginx's public folder
      - .:/usr/share/nginx/html
    restart: unless-stopped

